### PR TITLE
chore(deps): update styled-jsx to ^3.3.1

### PR DESCRIPTION
**Pull request by Gounlaf**
Fix for #519

## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

Update styled-jsx to ^3.3.1 to allow compatibility with react@^17

### CODE REVIEW

**Comment by unix** [comment]
[styled-jsx#695](https://github.com/vercel/styled-jsx/issues/695) This issue has not been fixed and will not be packaged even if we upgrade.
It is not possible to upgrade this dependency yet, so perhaps we should look for another solution to replace `styled-jsx`.

**Comment by unix** [comment]
Maybe the compatibility code in [695](https://github.com/vercel/styled-jsx/issues/695) is the way to go. (it's a way to add a hack to the runtime)

**Comment by Gounlaf** [comment]
Hi @unix,

Well, at least could it be frozen to `styled-jsx@3.3.1` instead of `styled-jsx@^3.3.1` ?

**Comment by unix** [comment]
> Well, at least could it be frozen to `styled-jsx@3.3.1` instead of `styled-jsx@^3.3.1` ?

The current version we have released is frozen in version `3.3.0`. I have tried to upgrade to `3.3.1`, but the `esm` package is buggy and I still need to test and debug the `esm` bundle. 😢 
It's really troublesome here, I will maintain this PR. (most of the work is needed to test the availability of the esm bundle)

**Comment by Gounlaf** [comment]
> I have tried to upgrade to `3.3.1`, but the `esm` package is buggy and I still need to test and debug the `esm` bundle. cry
> It's really troublesome here, I will maintain this PR. (most of the work is needed to test the availability of the esm bundle)

Okay =/.
I will stick to styled-js@3.3.0 / react@16 until https://github.com/vercel/styled-jsx/issues/695 is fixed.

Can't help you much around the `esm` bundle issues, my knowledge in js / ts / es modules are really limited

**Review by ofekashery — APPROVED** [review]

**Comment by unix** [comment]
I tried to fix this issue with dirty code and so far it seems to be compatible with React 17, I did some local testing of the module but can't guarantee the coverage of the module.
I have moved the target to the `rc` branch and plan to release a few `canary` versions as trial versions, and if there are no problems, I will point stable to the latest version later.

**Comment by unix** [comment]
@ofekashery 
Recently, Vercel often fails to build because the default cache cannot be removed and each build reverts to an earlier cache configuration, so we have to manually redeploy to clear the cache.
Right now Vercel cannot manually configure the cache... 😿

**Pull request merged**
