### PR TITLE
fix(typo): Dodcument -> Do Document

### PR DESCRIPTION
**Pull request by Deep-Codes**
## Change information

Typo Fixed.

### CODE REVIEW

**Review by unix — APPROVED** [review]
❤️

**Comment by unix** [comment]
@Deep-Codes 
Can you `rebase` the current branch to the end of the `master`? (we need to make sure that the master's history is clean)

**Comment by Deep-Codes** [comment]
> @Deep-Codes
> Can you `rebase` the current branch to the end of the `master`? (we need to make sure that the master's history is clean)

Done ✅

**Comment by unix** [comment]
Hmmm, looks like there's still a unneeded merge commit. (we can remove this unneeded commit)

**Comment by Deep-Codes** [comment]
> Hmmm, looks like there's still a unneeded merge commit. (we can remove this unneeded commit)

How to do that? 😅

**Comment by unix** [comment]
We need to update the origin source, then run `rebase`: `git upgrade origin && git rebase origin/master -i`.
I just forcefully pushed your branch and now everything is in place.

**Comment by Deep-Codes** [comment]
> We need to update the origin source, then run `rebase`: `git upgrade origin && git rebase origin/master -i`.
> I just forcefully pushed your branch and now everything is in place.

Thanks, Man! not great at it. Sorry 😅

**Pull request merged**
