### PR TITLE
Tabs scrollable

### PR DESCRIPTION
**Pull request by VaibhavAcharya**
## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information
- Added overflow to tabs
- Hid scrollbar on tabs
- Made menu sticker compatible with scrollable tabs by assigning correct width
- Added scroll behavior example in docs (english)
- Tab labels now no longer breaks on multiple lines

### CODE REVIEW

**Comment by unix** [comment]
Great, thanks!
Can you add an example to `Tabs` documentation to demonstrate this feature?
(Don't forget to run `yarn test-update` to update the snapshot.)

**Comment by VaibhavAcharya** [comment]
I was having some problem with width of .inner in menu-sticker but figured it out at last. Now this feat. is compete.

**Comment by VaibhavAcharya** [comment]
Is there anything else which needed to be worked on here or am I missing some formality ?

**Review by unix — APPROVED** [review]
👍

**Pull request merged**
