### PR TITLE
feature Update tabs-item.tsx

### PR DESCRIPTION
**Pull request by nikhilgupta58**
feature Add highlight on Tabs component #653

## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

### CODE REVIEW

**Comment by daviddossantos** [comment]
Hello @nikhilgupta58, insert `feature` before of the title your PR to pass the test.

**Comment by nikhilgupta58** [comment]
I have updated my title, now what to do?

**Comment by nikhilgupta58** [comment]
All tests are passed now, please merge it now

**Comment by nikhilgupta58** [comment]
Please merge my PR

**Comment by unix** [comment]
I have force pushed to your branch for complement this feature:

- Clean git history (the original PR is a one-line code change, but contains 6 commits)
- Restyled Tabs.Item
- Fixed a bug where Tab's animation was canceled by rendering.

and, this feature should not be released too soon. (need to wait until I fix other issues)

**Pull request merged**
